### ISSUE TITLE
提供的示例没有效果，readme中中文文档跳转失败

### ISSUE THREAD

**Issue by nadirvishun** [mizuka-wu/el-table-horizontal-scroll#2]
提供的[示例网址](https://www.mizuka.top/el-table-horizontal-scroll/index.html)中没有滚动条，与截图不一样，但实际本地引入插件后是正常的。

**Comment by mizuka-wu** [comment]
默认的是鼠标浮上去才显示

发自我的 iPhone

在 2022年10月13日，16:08，nadirvishun ***@***.***> 写道：

﻿

提供的示例网址<https://www.mizuka.top/el-table-horizontal-scroll/index.html>中没有滚动条，与截图不一样，但实际本地引入插件后是正常的。

**Comment by nadirvishun** [comment]
不管是always还是其它的都没有效果，还特意换了火狐等浏览器看都是没有的。

**Comment by mizuka-wu** [comment]
2？3？

发自我的 iPhone

在 2022年10月13日，16:43，nadirvishun ***@***.***> 写道：

﻿

不管是always还是其它的都没有效果，还特意换了火狐等浏览器看都是没有的。

**Comment by nadirvishun** [comment]
我本地用的是vue2可以正常显示，但不是运行的示例，而是直接在已有的项目上测试的。

**Comment by mizuka-wu** [comment]
最新demo已修复
