### ISSUE TITLE
除了'always'，'hover'，可以加一个不触发指令的Key吗？

### ISSUE THREAD

**Issue by Vue-ccl** [mizuka-wu/el-table-horizontal-scroll#21]
我想在特定的条件下，关闭吸底指令

**Comment by mizuka-wu** [comment]
加个enable参数吧

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Vue-ccl ***@***.***>
发送时间: Wednesday, June 5, 2024 11:13:10 AM
收件人: mizuka-wu/el-table-horizontal-scroll ***@***.***>
抄送: Subscribed ***@***.***>
主题: [mizuka-wu/el-table-horizontal-scroll] 除了'always'，'hover'，可以加一个不触发指令的Key吗？ (Issue #21)


我想在特定的条件下，关闭吸底指令

―

**Comment by Vue-ccl** [comment]
是的，谢谢

**Comment by mizuka-wu** [comment]
ok 这几天加一下

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Vue-ccl ***@***.***>
发送时间: Wednesday, June 5, 2024 11:19:57 AM
收件人: mizuka-wu/el-table-horizontal-scroll ***@***.***>
抄送: Edward Mizuka ***@***.***>; Comment ***@***.***>
主题: Re: [mizuka-wu/el-table-horizontal-scroll] 除了'always'，'hover'，可以加一个不触发指令的Key吗？ (Issue #21)


是的，谢谢

―
