### ISSUE TITLE
【建议】动态增加滚动条高度

### ISSUE THREAD

**Issue by nadirvishun** [mizuka-wu/el-table-horizontal-scroll#3]
目前滚动条的高度太小了，导致鼠标要非常精确才能定位到滚动条上，可否实现类似下图的这种，当鼠标移动到滚动条相关位置时，高度变高，方便抓取到滚动条。实在不行建议开放自定义高度。
![a](https://user-images.githubusercontent.com/5761981/195792175-d0557532-b629-4fb1-9299-ff74912e5091.gif)

**Comment by mizuka-wu** [comment]
用的el-scroller的class 可以增加一个css给我提个mr

发自我的 iPhone

在 2022年10月14日，15:52，nadirvishun ***@***.***> 写道：

﻿

目前滚动条的高度太小了，导致鼠标要非常精确才能定位到滚动条上，可否实现类似下图的这种，当鼠标移动到滚动条相关位置时，高度变高，方便抓取到滚动条。实在不行建议开放自定义高度。
[a]<https://user-images.githubusercontent.com/5761981/195792175-d0557532-b629-4fb1-9299-ff74912e5091.gif>

**Comment by mizuka-wu** [comment]
请自行修改class
