### ISSUE TITLE
能否增加一个class

### ISSUE THREAD

**Issue by ringgoyao** [mizuka-wu/el-table-horizontal-scroll#4]
![image](https://user-images.githubusercontent.com/5906943/197925525-14999dfd-2bb7-4b80-8215-3c2f9fe7e3b8.png)

我希望使用了该指令的el-table 可以默认增加一个class，比如el-table-bottom-scroll，这样我可以通过此class全局隐藏 table上的滚动条

**Comment by mizuka-wu** [comment]
提个mr我来合

发自我的 iPhone

在 2022年10月26日，11:09，ringgoyao ***@***.***> 写道：

﻿

[image]<https://user-images.githubusercontent.com/5906943/197925218-1dbae21b-73dd-4437-a0be-eb02a25d93d9.png>
我希望使用了该指令的el-table 可以增加一个class，比如el-table-bottom-scroll，这样我可以全局隐藏 table上的滚动条，
不知道是否可以？

**Comment by mizuka-wu** [comment]
el-table-horizontal-scrollbar
