### ISSUE TITLE
浏览器 拖动resize的时候 模拟的横向滚动条 与真实的table滚动条宽度有出入

### ISSUE THREAD

**Issue by Corgis** [mizuka-wu/el-table-horizontal-scroll#5]
感谢作者提供这个插件，使用的很棒，目前使用中有看到个bug
如图 红色是真实的滚动条，灰色是模拟的滚动条 宽度表现不一致
![image](https://user-images.githubusercontent.com/13865529/223378403-30e995da-c3de-49c9-8d22-b757def37df8.png)

**Comment by mizuka-wu** [comment]
目前直接采用了el-scroller的样式 应该是这个问题

发自我的 iPhone

在 2023年3月7日，17:18，Corgis ***@***.***> 写道：

﻿

感谢作者提供这个插件，使用的很棒，目前使用中有看到个bug
如图 红色是真实的滚动条，灰色是模拟的滚动条 宽度表现不一致
[image]<https://user-images.githubusercontent.com/13865529/223378008-56586da4-5c45-47d4-ae72-b03f6de42488.png>

**Comment by Corgis** [comment]
感谢作者回复，会考虑有空的时候修复这个问题么？目前拖动浏览器resize 或者 布局变化后 模拟的滚动条的真实的长度不一致

**Comment by mizuka-wu** [comment]
可以的 不过可能就无脑上一个resize observer

发自我的 iPhone

在 2023年3月7日，17:37，Corgis ***@***.***> 写道：

﻿

感谢作者回复，会考虑有空的时候修复这个问题么？目前拖动浏览器resize 或者 布局变化后 模拟的滚动条的真实的长度不一致

**Comment by Corgis** [comment]
哈哈
