### ISSUE TITLE
可以自定义高度吗？

### ISSUE THREAD

**Issue by ZhouXianYu-Kennedy** [mizuka-wu/el-table-horizontal-scroll#9]
你好，非专业前端
请问可以自定义滚动条高度吗？
设置brightness为0.9甚至100感觉还是非常暗呢？
谢谢！

**Comment by mizuka-wu** [comment]
最新版有提供额外的类名出来 改那个类相关样式就行

发自我的 iPhone

在 2023年4月17日，17:26，Jame Zhou ***@***.***> 写道：

﻿

你好，非专业前端
请问可以自定义高度吗？
设置brightness感觉还是非常暗呢？
谢谢！
